import { z } from "zod";

export const RentalHistoryEntrySchema = z.object({
  timestamp: z.string(),
  query: z.string(),
  listingId: z.string(),
  source: z.string(),
  title: z.string(),
  url: z.string(),
  location: z.string(),
  rentBRL: z.number(),
  condominioBRL: z.number().nullable(),
  iptuMensalBRL: z.number().nullable(),
  monthlyTotalBRL: z.number(),
  currency: z.string(),
  tipo: z.string(),
  areaM2: z.number().nullable(),
  quartos: z.number().nullable(),
  suites: z.number().nullable(),
  banheiros: z.number().nullable(),
  vagas: z.number().nullable(),
  bairro: z.string().nullable(),
  cidade: z.string().nullable(),
  uf: z.string().nullable(),
  andar: z.number().nullable(),
  mobiliado: z.boolean().nullable(),
  aceitaPet: z.boolean().nullable(),
  previousMonthlyTotal: z.number().nullable(),
  monthlyChange: z.number().nullable(),
  changePercent: z.number().nullable(),
  observationCount: z.number().int().nonnegative(),
  rating: z.string().nullable(),
  fairMonthlyTotal: z.number().nullable(),
  deltaPercent: z.number().nullable(),
  pricePerM2: z.number().nullable(),
  benchmarkScope: z.string().nullable(),
  benchmarkLabel: z.string().nullable(),
  benchmarkSampleSize: z.number().nullable(),
  warnings: z.string().nullable(),
  ratingReasoning: z.string().nullable(),
});

export type RentalHistoryEntry = z.infer<typeof RentalHistoryEntrySchema>;
